use_frameworks!

target 'BlinkingLabel_Example' do
  pod 'BlinkingLabel', :path => '../'

  target 'BlinkingLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
